config/routes.rb
Rails.application.routes.draw do
  get 'page/happy'

  get 'page/hour'

  resources :restaurans
  get 'pages/about'

  get 'pages/contact'

  root 'restaurans#index'

end

app/models/restauran.rb
class Restauran < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def happy
  end

  def hour
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurans_controller.rb
class RestauransController < ApplicationController
  before_action :set_restauran, only: [:show, :edit, :update, :destroy]

  # GET /restaurans
  # GET /restaurans.json
  def index
    @restaurans = Restauran.all
  end

  # GET /restaurans/1
  # GET /restaurans/1.json
  def show
  end

  # GET /restaurans/new
  def new
    @restauran = Restauran.new
  end

  # GET /restaurans/1/edit
  def edit
  end

  # POST /restaurans
  # POST /restaurans.json
  def create
    @restauran = Restauran.new(restauran_params)

    respond_to do |format|
      if @restauran.save
        format.html { redirect_to @restauran, notice: 'Restauran was successfully created.' }
        format.json { render :show, status: :created, location: @restauran }
      else
        format.html { render :new }
        format.json { render json: @restauran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurans/1
  # PATCH/PUT /restaurans/1.json
  def update
    respond_to do |format|
      if @restauran.update(restauran_params)
        format.html { redirect_to @restauran, notice: 'Restauran was successfully updated.' }
        format.json { render :show, status: :ok, location: @restauran }
      else
        format.html { render :edit }
        format.json { render json: @restauran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurans/1
  # DELETE /restaurans/1.json
  def destroy
    @restauran.destroy
    respond_to do |format|
      format.html { redirect_to restaurans_url, notice: 'Restauran was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restauran
      @restauran = Restauran.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restauran_params
      params.require(:restauran).permit(:name, :address, :phone, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurans_helper.rb
module RestauransHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright Patrick Exil</p>

app/views/layouts/_navbar.htlm.erb
<p>Copyright Patrick Exil</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bocahappyhours</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

   <!-- Optional theme -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

   <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Happy Hours</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/pages/about">About <span class="sr-only">(current)</span></a></li>
        <li><a href="/pages/contact">contact</a></li>
     
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    
      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container-fluid">
  <%= yield %>
  <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/page/happy.html.erb
<h1>Page#happy</h1>
<p>Find me in app/views/page/happy.html.erb</p>

app/views/page/hour.html.erb
<h1>Page#hour</h1>
<p>Find me in app/views/page/hour.html.erb</p>

app/views/pages/about.html.erb
<h1>Welcome To Boca Happy Hours</h1>
<p>Best Happy Hours Finder </p>

app/views/pages/contact.html.erb
<h1>We Would Love To Hear From You</h1>
<p>Contact Us at exil26@gmail.com</p>

app/views/restaurans/_form.html.erb
<%= form_for(@restauran) do |f| %>
  <% if @restauran.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restauran.errors.count, "error") %> prohibited this restauran from being saved:</h2>

      <ul>
      <% @restauran.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address,  class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone,  class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website,  class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
      </div>
<% end %>

app/views/restaurans/edit.html.erb
<h1>Editing Restauran</h1>

<%= render 'form' %>

<%= link_to 'Show', @restauran, class: "btn btn-link" %> |
<%= link_to 'Back', restaurans_path, class: "btn btn-link" %>

app/views/restaurans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurans</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurans.each do |restauran| %>
      <tr>
        <td><%= restauran.name %></td>
        <td><%= restauran.address %></td>
        <td><%= restauran.phone %></td>
        <td><%= restauran.website %></td>
        <td><%= link_to 'Show', restauran, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_restauran_path(restauran) %></td>
        <td><%= link_to 'Destroy', restauran, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restauran', new_restauran_path, class: "btn btn-link" %>

app/views/restaurans/new.html.erb
<h1>New Restauran</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurans_path, class: "btn btn-link" %>

app/views/restaurans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restauran.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restauran.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restauran.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @restauran.website %>
</p>

<%= link_to 'Edit', edit_restauran_path(@restauran), class: "btn btn-link" %> |
<%= link_to 'Back', restaurans_path, class: "btn btn-link" %>